site:
  title: Deploying Lightbend applications to OpenShift
  url: https://developer.lightbend.com/guides/openshift-deployment/
  start_page: tutorials:ROOT:index.adoc

content:
  sources:
  - url: .
    branches: HEAD

ui:
  bundle:
    url: https://github.com/lightbend/antora-ui-lightbend-theme/raw/master/build/ui-bundle.zip
    snapshot: true

output:
   clean: true
