site:
  title: Deploying Lightbend applications to OpenShift
  url: https://developer.lightbend.com/guides/openshift-deployment/
  start_page: Tutorials:ROOT:index.adoc

content:
  sources:
  - url: .
    branches: HEAD

ui:
  bundle:
    url: ./ui-bundle.beta.zip

output:
   clean: true
